### ISSUE TITLE
llama-index Dependency for spider-client

### ISSUE THREAD

**Issue by tarujg** [spider-rs/spider-clients#6]
The llama-index-readers-web depend on an outdated version of the spider client - which is not being picked up since the spider-client = "^0.0.11".

The following [reference](https://github.com/run-llama/llama_index/blob/c9225877bc45a8242a27e7872a3f8269ef818d2a/llama-index-integrations/readers/llama-index-readers-web/pyproject.toml#L59) is pinned to the older version. Is there any reason why we have pinned it to version 0.0.11 for this as a dependency?

Can we upgrade it in llama-index?

**Comment by j-mendez** [comment]
> The llama-index-readers-web depend on an outdated version of the spider client - which is not being picked up since the spider-client = "^0.0.11".
> 
> The following [reference](https://github.com/run-llama/llama_index/blob/c9225877bc45a8242a27e7872a3f8269ef818d2a/llama-index-integrations/readers/llama-index-readers-web/pyproject.toml#L59) is pinned to the older version. Is there any reason why we have pinned it to version 0.0.11 for this as a dependency?
> 
> Can we upgrade it in llama-index?

Yes, should be safe to upgrade.

**Comment by gbertb** [comment]
this should be fixed in the next release of llama-index

**Comment by tarujg** [comment]
@gbertb do we need to keep on adding this regularly to keep the spider-client updates better and more flexible to updates in these endpoints that you support?



> 21.19     The user requested spider-client==0.0.68
> 21.19     llama-index-readers-web 0.2.1 depends on spider-client<0.0.28 and >=0.0.27

**Comment by j-mendez** [comment]
> @gbertb @j-mendez do we need to keep on adding this regularly to keep the spider-client updates better and more flexible to updates in these endpoints that you support?
> 
> > 21.19     The user requested spider-client==0.0.68
> > 21.19     llama-index-readers-web 0.2.1 depends on spider-client<0.0.28 and >=0.0.27

Hi @tarujg good question. Yes and no, for the most part all the core of the functionality is lifted off the clients. We mainly need it for types and easy conventions for the API endpoints. We have a couple new shapes for the params coming soon, the updates for params are not often so it should be low lift when the time comes.
